services:
  - type: web
    name: todo-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString
      - key: ACCESS_JWT_SECRET
        generateValue: true
      - key: REFRESH_JWT_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: todo-db
    databaseName: todo
    user: todo_user
    plan: free
